name: ci

on:
    push:
    pull_request:

jobs:
    check:
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - run: bun install --frozen-lockfile
            - run: bun run fmt:check
            - run: bun run check
            - run: bun test
            - run: bun run build
